# version: '3.8'

# services:
#   ms-aula:
#     build: .
#     container_name: ms-aula
#     restart: always
#     ports:
#       - "8100:5000"
#     networks:
#       - rede-compartilhada
#     #entrypoint: ["/bin/sh", "-c", "until nc -z meu-postgres 5432; do echo Waiting for database; sleep 2; done; dotnet ms-aula.dll"]

# networks:
#   rede-compartilhada:
#     external: true

version: '3.8'

services:
  ms-aula:
    build: .
    container_name: ms-aula
    ports:
      - "5001:5001"
    networks:
      - rede-compartilhada
    environment:
      - DB_HOST=ms-aula-db
      - DB_NAME=aula_db
      - DB_USER=aula_user
      - DB_PASS=aula_pass
      - MS_USUARIO_URL=http://ms-usuario:5000  # Serviço ms-usuario está na mesma rede
    depends_on:
      - ms-aula-db
      - ms-usuario

  ms-aula-db:
    image: postgres:latest
    container_name: ms-aula-db
    environment:
      POSTGRES_USER: aula_user
      POSTGRES_PASSWORD: aula_pass
      POSTGRES_DB: aula_db
    volumes:
      - ms-aula-db-data:/var/lib/postgresql/data
    networks:
      - rede-compartilhada

networks:
  rede-compartilhada:
    external: true

volumes:
  ms-aula-db-data:
