# version: '3.8'

# services:
#   app:
#     build: .
#     ports:
#       - "8100:5000" # Porta para acessar o aplicativo no host
#       #- "8101:5001" # Porta HTTPS no host para o container
#     depends_on:
#       - postgres
#     environment:
#       - ConnectionStrings__DbContext=Host=ms-aula-postgres-1;Port=5432;Pooling=true;Database=site-fisica;User Id=postgres;Password=admin
#     networks:
#       - default

#   postgres:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: admin
#       POSTGRES_DB: site-fisica
#     ports:
#       - "5432:5432"
#     networks:
#       - default

# networks:
#   default:
#     name: rede-compartilhada
#     external: true
version: '3.8'

services:
  ms-aula:
    build: .
    container_name: ms-aula
    restart: always
    ports:
      - "8100:5000"
    depends_on:
      - meu-postgres
    networks:
      - rede-compartilhada
    #entrypoint: ["/bin/sh", "-c", "until nc -z meu-postgres 5432; do echo Waiting for database; sleep 2; done; dotnet ms-aula.dll"]

networks:
  rede-compartilhada:
    external: true